/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void led_config()
{
	RCC->AHB1ENR |=(1<<1);         //ENABLING BUS FOR PORT B

	GPIOB->MODER &=~(3<<30);       //CLEARING THE BITS IN PORT B FOR PIN 15(LED 2)
	GPIOB->MODER |=(1<<30);        //DECLARING THE OUTPUT MODE

	GPIOB->MODER &=~(3<<28);       //CLEARING THE BITS IN PORT B FOR PIN 14(LED 3)
	GPIOB->MODER |=(1<<28);        //DECLARING THE OUTPUT MODE

	GPIOB->MODER &=~(3<<26);       //CLEARING THE BITS IN PORT B FOR PIN 13(LED 4)
	GPIOB->MODER |=(1<<26);        //DECLARING THE OUTPUT MODE

	RCC->AHB1ENR |=(1<<2);         //ENABLING THE BUS FOR PORT C

	GPIOC->MODER &=~(3<<12);       //CLEARING THE BITS IN PORT C FOR PIN 6(LED 1)
	GPIOC->MODER |=(1<<12);        //DECLARING THE OUTPUT MODE

	GPIOC->ODR |=(1<<6);           //SWITCHING OFF THE LED
	GPIOB->ODR |=(1<<13);
	GPIOB->ODR |=(1<<14);
	GPIOB->ODR |=(1<<15);

}

void switch_config()
{
	RCC->AHB1ENR |=(1<<0);         //ENABLE THE BUS PORT A

	GPIOA->MODER &=~(3<<30);       //DECLARING THE PORT A PIN 15 AS INPUT

	GPIOB->MODER &=~(3<<14);       //DECLARING THE PORT B, PIN 7 AS INPUT

	GPIOB->MODER &=~(3<<6);       //DECLARING THE PORT B, PIN 3 AS INPUT

	GPIOB->MODER &=~(3<<8);       //DECLARING THE PORT B, PIN 4 AS INPUT

}

void Interrupt_Handler()
{
	RCC->APB2ENR |=(1<<14);       //ENABLE THE BUS FOR SYSTEM CONFIGURATION

	SYSCFG->EXTICR[1] |=(0x1<<12);   //DECLARE THE INTERRUPT AS EXTI7 IN PORT B
    SYSCFG->EXTICR[1] |=(0x1<<0);    //DECLARE THE INTERRUPT AS EXTI4 IN PORT B
    SYSCFG->EXTICR[0] |=(0x1<<12);   //DECLARE THE INTERRUPT AS EXTI3 IN PORRT B
    SYSCFG->EXTICR[3] |=(0x0<<12);   //DECALRE THE INTERRUPT AS EXTI15 IN PORT A


    EXTI->FTSR |=(1<<7);             //SELECTING THE RISING TRIGGER FOR PB7
    EXTI->FTSR |=(1<<3);             //SELECTING THE RISING TRIGGER FOR PB3
    EXTI->FTSR |=(1<<4);             //SELECTING THE RISING TRIGGER FOR PB4
    EXTI->FTSR |=(1<<15);             //SELECTING THE RISING TRIGGER FOR PA15

    EXTI->IMR |=(1<<7);              //NON-MASKING THE INTERRUPT FOR PB7
    EXTI->IMR |=(1<<3);              //NON-MASKING THE INTERRUPT FOR PB3
    EXTI->IMR |=(1<<4);              //NON-MASKING THE INTERRUPT FOR PB4
    EXTI->IMR |=(1<<15);             //NON-MASKING THE INTERRUPT FOR PA15


    NVIC_EnableIRQ(EXTI3_IRQn);      //CALLING THE EXTERNAL INTERRUPT FOR PB3
    NVIC_EnableIRQ(EXTI4_IRQn);       //CALLING THE EXTERNAL INTERRUPT FOR PB4
    NVIC_EnableIRQ(EXTI9_5_IRQn);    //CALLING THE EXTERNAL INTERRUPT FOR PB7
    NVIC_EnableIRQ(EXTI15_10_IRQn);  //CALLING THE EXTERNAL INTERRUPT FOR PA15



}
void EXTI9_5_IRQHandler(void){
	if((EXTI->PR)&(1<<7))
	{
		GPIOC->ODR ^=(1<<6);
		for(int i=0;i<300000;i++);
		EXTI->PR=(1<<7);
	}

}
void EXTI3_IRQHandler(void){
	if((EXTI->PR>>3)&1)
	{
		GPIOB->ODR ^=(1<<15);
		for(int i=0;i<300000;i++);
		EXTI->PR=(1<<3);
	}

}
void EXTI4_IRQHandler(void){
	if((EXTI->PR)&(1<<4))
	{
		GPIOB->ODR ^=(1<<14);
		for(int i=0;i<300000;i++);
		EXTI->PR=(1<<4);
	}
}
void EXTI15_10_IRQHandler(void){
	if((EXTI->PR)&(1<<15))
	{
		GPIOB->ODR ^=(1<<13);
		for(int i=0;i<300000;i++);
		EXTI->PR=(1<<15);
	}
}
int main(void)
{
	led_config();
	switch_config();
	Interrupt_Handler();


    /* Loop forever */
	for(;;);
}
